### ISSUE TITLE
Trees will not grow, SPC Support, Frequent Crashes and Whitescreens while using mods and improve leaf shadowing

### ISSUE THREAD

**Issue by StereoMadnessss** [Joe4422/bta-issues#1]
1: Some Tree Types Refuse to grow. This issue is major but not too major.

2: Commands are very primitive

3: Ids for blocks were changed to different ids and this connects to 2, it can also cause corruption to worlds upgrading to better than adventure from vanilla beta 1.7.3

4: Frequent Crashes and Whitescreens when using Mods (SPC makes Better than Adventure unusable because of the lack to play singleplayer, and TooManyItems crashes when opening the inventory gui because it interferes with the mod)

Video Showing all of the bugs that I could replicate in action:
[https://youtu.be/1DQ8ZEdMmfs](https://youtu.be/1DQ8ZEdMmfs)

OS: MacOS 11.6.1
Mod Version: 1.7.6 (MultiMC Instance)

**Comment by SkyDeckAGoGo** [comment]
Hi! Thanks for the feedback, i have a couple of notes/clarifications if thats okay with you first

1: We will look into that, thank you for the heads up

2: Not really a bug report in my eyes but we do plan to upgrade commands in the next update.

3: if you personally have had corruptions happen we need to know about that, including any pictures, world downloads before/after corruptions etc.. other than that, we do have a world converter built into BTA for 1.7.3 worlds that should convert any IDs to the new ID system. So ideally corruptions should not occur unless you are trying to run a bta world in vanilla beta, which we don't recommend regardless. As for the IDs, we do allow block names for the /give command which should eliminate the need to use IDs.

4: like i've mentioned on the forum post, existing beta mods are not supported by BTA. The codebase is too different from vanilla 1.7.3 therefore expect no existing mods to work with the mod. We are planning to provide support for people to make mods for BTA, but as for existing mod support, its not planned and running BTA with existing mods is not recommended.

Hope this info is helpful! Any more questions feel free to ask.
